# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_region_name', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
