# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='buyer_address_encode',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='buyer_district_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='buyer_name_encode',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='buyer_phone_encode',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='carrier_service_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='email_encode',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_expected_delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_status',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_method',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='reason_cancel',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='store_id_encode',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
