# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sendo', '0002_auto_20171021_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantity', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendo.SalesOrder')),
            ],
        ),
    ]
