# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendo', '0005_auto_20171021_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklisthistory',
            old_name='blacklist_phone_id',
            new_name='blacklist_phone',
        ),
        migrations.RenameField(
            model_name='salesorderdetail',
            old_name='sales_order_id',
            new_name='sales_order',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='sales_order_id',
            new_name='sales_order',
        ),
    ]
